#ifndef JOY_BUTTON_MAP_H
#define JOY_BUTTON_MAP_H
#include <string>
using namespace std;

extern string joy_button_maps[151][3] = {{"-1","None",""},
                        {"0","Button 0","0"},
                        {"1","Button 1","1"},
                        {"2","Button 2","2"},
                        {"3","Button 3","3"},
                        {"4","Button 4","4"},
                        {"5","Button 5","5"},
                        {"6","Button 6","6"},
                        {"7","Button 7","7"},
                        {"8","Button 8","8"},
                        {"9","Button 9","9"},
                        {"10","Button 10","10"},
                        {"11","Button 11","11"},
                        {"12","Button 12","12"},
                        {"13","Button 13","13"},
                        {"14","Button 14","14"},
                        {"15","Button 15","15"},
                        {"16","Button 16","16"},
                        {"17","Button 17","17"},
                        {"18","Button 18","18"},
                        {"19","Button 19","19"},
                        {"20","Button 20","20"},
                        {"21","Button 21","21"},
                        {"22","Button 22","22"},
                        {"23","Button 23","23"},
                        {"24","Button 24","24"},
                        {"25","Button 25","25"},
                        {"26","Button 26","26"},
                        {"27","Button 27","27"},
                        {"28","Button 28","28"},
                        {"29","Button 29","29"},
                        {"30","Button 30","30"},
                        {"31","Button 31","31"},
                        {"32","Button 32","32"},
                        {"33","Button 33","33"},
                        {"34","Button 34","34"},
                        {"35","Button 35","35"},
                        {"36","Button 36","36"},
                        {"37","Button 37","37"},
                        {"38","Button 38","38"},
                        {"39","Button 39","39"},
                        {"40","Button 40","40"},
						{"41","Esc","KEY_ESC"},
						{"42","1","KEY_1"},
						{"43","2","KEY_2"},
						{"44","3","KEY_3"},
						{"45","4","KEY_4"},
						{"46","5","KEY_5"},
						{"47","6","KEY_6"},
						{"48","7","KEY_7"},
						{"49","8","KEY_8"},
						{"50","9","KEY_9"},
						{"51","0","KEY_0"},
						{"52","-","KEY_MINUS"},
						{"53","=","KEY_EQUAL"},
						{"54","+","KEY_BACKSPACE"},
						{"55","TAB","KEY_TAB"},
						{"56","q","KEY_Q"},
						{"57","w","KEY_W"},
						{"58","e","KEY_E"},
						{"59","r","KEY_R"},
						{"60","t","KEY_T"},
						{"61","y","KEY_Y"},
						{"62","u","KEY_U"},
						{"63","i","KEY_I"},
						{"64","o","KEY_O"},
						{"65","p","KEY_P"},
						{"66","{","KEY_LEFTBRACE"},
						{"67","}","KEY_RIGHTBRACE"},
						{"68","Enter","KEY_ENTER"},
						{"69","L_Ctrl","KEY_LEFTCTRL"},
						{"70","a","KEY_A"},
						{"71","s","KEY_S"},
						{"72","d","KEY_D"},
						{"73","f","KEY_F"},
						{"74","g","KEY_G"},
						{"75","h","KEY_H"},
						{"76","j","KEY_J"},
						{"77","k","KEY_K"},
						{"78","l","KEY_L"},
						{"79",";","KEY_SEMICOLON"},
						{"80","'","KEY_APOSTROPHE"},
						{"81","'","KEY_GRAVE"},
						{"82","L_Shift","KEY_LEFTSHIFT"},
						{"83","\\","KEY_BACKSLASH"},
						{"84","z","KEY_Z"},
						{"85","x","KEY_X"},
						{"86","c","KEY_C"},
						{"87","v","KEY_V"},
						{"88","b","KEY_B"},
						{"89","n","KEY_N"},
						{"90","m","KEY_M"},
						{"91",",","KEY_COMMA"},
						{"92",".","KEY_DOT"},
						{"93","/","KEY_SLASH"},
						{"94","R Shift","KEY_RIGHTSHIFT"},
						{"95","*","KEY_KPASTERISK"},
						{"96","L Alt","KEY_LEFTALT"},
						{"97","Space","KEY_SPACE"},
						{"98","CapsLock","KEY_CAPSLOCK"},
						{"99","F1","KEY_F1"},
						{"100","F2","KEY_F2"},
						{"101","F3","KEY_F3"},
						{"102","F4","KEY_F4"},
						{"103","F5","KEY_F5"},
						{"104","F6","KEY_F6"},
						{"105","F7","KEY_F7"},
						{"106","F8","KEY_F8"},
						{"107","F9","KEY_F9"},
						{"108","F10","KEY_F10"},
						{"109","Num Lock","KEY_NUMLOCK"},
						{"110","Scroll Lock","KEY_SCROLLLOCK"},
						{"111","Pad 7","KEY_KP7"},
						{"112","Pad 8","KEY_KP8"},
						{"113","Pad 9","KEY_KP9"},
						{"114","Pad -","KEY_KPMINUS"},
						{"115","Pad 4","KEY_KP4"},
						{"116","Pad 5","KEY_KP5"},
						{"117","Pad 6","KEY_KP6"},
						{"118","Pad 7","KEY_KPPLUS"},
						{"119","Pad 1","KEY_KP1"},
						{"120","Pad 2","KEY_KP2"},
						{"121","Pad 3","KEY_KP3"},
						{"122","Pad 0","KEY_KP0"},
						{"123","Pad .","KEY_KPDOT"},
/*						{"124","","KEY_ZENKAKUHANKAKU"},
						{"125","","KEY_102ND"},*/
						{"124","F11","KEY_F11"},
						{"125","F12","KEY_F12"},
/*						{"","","KEY_RO"},
						{"","","KEY_KATAKANA"},
						{"","","KEY_HIRAGANA"},
						{"","","KEY_HENKAN"},
						{"","","KEY_KATAKANAHIRAGANA"},
						{"","","KEY_MUHENKAN"},
						{"","","KEY_KPJPCOMMA"},*/
						{"126","Pad Enter","KEY_KPENTER"},
						{"127","R Ctrl","KEY_RIGHTCTRL"},
						{"128","Pad /","KEY_KPSLASH"},
						{"129","Sysreq","KEY_SYSRQ"},
						{"130","R Alt","KEY_RIGHTALT"},
						{"131","Return","KEY_LINEFEED"},
						{"132","Home","KEY_HOME"},
						{"133","Up","KEY_UP"},
						{"134","PgUp","KEY_PAGEUP"},
						{"135","Left","KEY_LEFT"},
						{"136","Right","KEY_RIGHT"},
						{"137","End","KEY_END"},
						{"138","Down","KEY_DOWN"},
						{"139","PgDown","KEY_PAGEDOWN"},
						{"140","Insert","KEY_INSERT"},
						{"141","Del","KEY_DELETE"},
						{"142","Macro","KEY_MACRO"},
						{"143","Mute","KEY_MUTE"},
						{"144","Vol-","KEY_VOLUMEDOWN"},
						{"145","Vol+","KEY_VOLUMEUP"},
						{"146","^","KEY_POWER"},
						{"147","Pad =","KEY_KPEQUAL"},
						{"148","Pad -","KEY_KPPLUSMINUS"},
						{"148","Pause","KEY_PAUSE"}};
#endif //JOY_BUTTON_MAP_H
